apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc-bets
config:
  # nome do nosso helm
  client_id: "kong"
  # client_secret: "g4isONaheW69prXcO4Fp5Kz6Azi6w5Km"
  client_secret: "GHvGsIM35kMDPnkN71O4EqzUGq0MvOEA"
  # o nome http://keycloak.iam é o nome do nosso service + name_space formando assim
  #keycloack = nome do nosso service
  #iam = nome do nosso namespace 
  # http://nome_do_service.namespace
  #realms/nome_do_nosso_helm/.well-known/openid-configuration
  discovery: "http://keycloak.iam/realms/bets/.well-known/openid-configuration"
  introspection_endpoint: "http://keycloak.iam/realms/bets/protocol/openid-connect/token/introspect"
  # Essas informações fazem a validação com a chave pública, mesma coisa que no Laravel, faz a autenticação
  # Depois que faz a validação só ficar verificando com a chave pública para verificar a autenticidade do token
  bearer_only: "yes"
  bearer_jwt_auth_enable: "yes"
  bearer_jwt_auth_allowed_auds:
    - account
plugin: oidc
