apiVersion: v1
kind: Service
metadata:
  annotations:
  # Declarando essa informação com o true vamos usar o mecanismo do kubernets
  # para fazer o loadbalancer do kubernets e não do Kong
    ingress.kubernetes.io/service-upstream : "true"
  labels:
    app: bets
    stack: echo
    interface: rest
    language: golang
  name: bets
spec:
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: bets
