apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matches
  namespace: argocd
  # O conceito do finzalizer é de quando nosso yml for removido faz a remoção por completa na aplicação
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  #Onde o nosso argo vai ficar escutando sendo apontado para 
  source:
    # caminho da pasta onde vamos ficar escutando, quando tiver alguma alteração nesse path
    # Iremos aplicar o matche
    path: deployments/matches
    #repositório que fazemos o rastreio, só mudar o endereço para o repositório que quer monitorar
    repoURL: https://github.com/codeedu/fc-api-gateway-k8s-matches-app.git
    # Esse head é um alias da branch main
    targetRevision: HEAD
    # Tomo do arquivo alvo
    helm:
      valueFiles:
        - values-kong.yaml
    # Aqui é o nosso caminho que iremos apontar as mudanças, no caso o mesmo namespace
  destination:
    namespace: bets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    # Se não tiver o nomespace para criar
    syncOptions:
      - CreateNamespace=true
